port: "8080"
auth:
  secret: "secret_example"
  header: "Token"
  ignore:
    - /auth/login
    - /auth/register
    - /auth/register/confirm
    - /auth/register/resend
cors:
  AllowedOrigin: "http://localhost:3000"
postgres:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password: "2153"
  dbname: "postgres"
redis:
  rport: "localhost:6379"
  rpassword: ""
service:
  storageDir: "../storage"
  tmpUpload: "../tmpUploads"
  secret: "secret_example"
  host: "localhost:8080"
SMTP:
  Host:     "secret"
  Port:     2525
  Username: "secret"
  Password: "secret"
  From:     "secret"