port: "8080"
cors:
  AllowedOrigin: "http://localhost:3000"
postgres:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password: "2153"
  dbname: "postgres"
service:
  storageDir: "../storage"
  tmpUpload: "../tmpUploads"
  secret: "secret_example"
  url_ttl_seconds: 300
  host: "localhost:8080"