version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: cloud-storage-postgres
    environment:
      POSTGRES_PASSWORD: "2153"
      POSTGRES_USER:     "postgres"
      POSTGRES_DB:       "cloudstorage"
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: cloud-storage-redis
    ports:
      - "6379:6379"
    restart: always